---

- name: Install packages needed for python development
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-setuptools
    - python-dev
    - build-essential

- name: Install pip
  apt: pkg=python-pip  state=latest
  sudo: yes

- name: Install virtualenv via pip
  pip: name=virtualenv
  sudo: yes
