---

- name: Install packages needed for python development
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-setuptools
    - python-dev
    - python2.7-dev
    - python-software-properties
    - libpq-dev

- name: Install third-party libraries
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - libtiff4-dev
    - libjpeg8-dev
    - zlib1g-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - tcl8.5-dev
    - tk8.5-dev

- name: Install pip
  apt: pkg=python-pip  state=latest
  sudo: yes

- name: Install virtualenv via pip
  pip: name=virtualenv
  sudo: yes
