---

- name: update apt cache and all packages to the latest version
  apt: upgrade=dist update_cache=yes cache_valid_time=43200

- name: Install git
  apt: pkg=git state=latest

- name: Install fail2ban
  apt: pkg=fail2ban state=latest
  notify:
    - ensure fail2ban

- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - tree
    - psmisc
    - chkrootkit
    - ufw
    - curl
    - gnupg
    - zip
    - rsync
    - wget
    - cron
    - keychain

- name: Install vim
  apt: pkg=vim state=latest
