---

- name: update apt cache
  apt: update_cache=yes

- name: Install git
  apt: pkg=git state=latest

- name: Install fail2ban
  apt: pkg=git state=latest
  notify:
    - ensure fail2ban

- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - build-essential
    - tree
    - psmisc
    - chkrootkit
    - ufw
    - curl
    - gnupg
    - zip
    - rsync
    - wget
    - cron

- name: Install vim
  apt: pkg=vim state=latest
