---

- name: install packages
  apt: pkg={{ item }} state=latest
  register: redis_install
  with_items:
    - tcl8.5
    - redis-server
  notify:
    - restart redis

- name: copy config template 
  template: 
    src: "redis.conf"
    dest: "/etc/redis/redis.conf"
  notify:
    - restart redis
