---

- name: Install postgresql
  apt: pkg={{ item }} state=latest
  with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
  notify:
    - restart postgres

- name: Required for python
  pip: name=psycopg2

- name: Create a new database
  sudo_user: postgres
  postgresql_db: 
    name: "{{ db_name }}"
    port: "{{ db_port }}"

- name: Ensure user has access to database
  sudo_user: postgres
  postgresql_user:
    db: "{{ db_name }}"
    name: "{{ psql_role }}"
    password: "{{ psql_role_password }}"
    priv: ALL
    role_attr_flags: SUPERUSER
