---

- name: installing supervisor
  apt: pkg=supervisor state=latest

- name: create log directory
  file: 
    path: "/home/{{ user }}/logs"
    state: "directory"

- name: create log files
  file: 
    path: "/home/{{ user }}/logs/{{ item }}"
    state: touch
  with_items:
    - 'gunicorn.err.log'
    - 'gunicorn.out.log'
    - 'celery.err.log'
    - 'celery.out.log'

- name: copy test template 
  template: 
    src: "{{ item }}"
    dest: "/etc/supervisor/conf.d"
  with_items:
    - 'gunicorn.conf'
    - 'celery.conf'
  notify:
    - restart supervisor 

- name: manage the state of program to be in 'started' state. 
  supervisorctl: 
    name: "{{ item }}"
    state: started
  with_items:
    - 'gunicorn'
    - 'celery'