---
- hosts: all
  tasks:
    - name: update apt cache
      apt: update_cache=yes
      sudo: yes

    - name: Installs nginx web server
      apt: pkg=nginx state=latest update_cache=true
      notify:
        - start nginx
      sudo: yes

    - name: Installs git
      apt: pkg=git state=latest
      sudo: yes


  handlers:
    - name: start nginx
      service: name=nginx state=started
      sudo: yes
