---

- name: Defining users
  hosts: all
  sudo: yes
  roles:
    - role: users

- name: Update server and install utils
  hosts: all
  sudo: yes
  roles:
    - role: common

- name: Install packages needed for python development
  hosts: all
  sudo: yes
  roles:
    - role: python-utils

- name: Setup nginx
  hosts: all
  sudo: yes
  roles:
    - role: nginx

- name: Setup PostgreSQL
  hosts: all
  sudo: yes
  roles:
    - role: postgresql

- name: Setup redis
  hosts: all
  sudo: yes
  roles:
    - role: redis

- name: Setup webapp
  hosts: all
  sudo: yes
  roles:
    - role: webapp

- name: Setup gunicorn scripts
  hosts: all
  sudo: yes
  roles:
    - role: gunicorn

- name: Setup celery script
  hosts: all
  sudo: yes
  roles:
    - role: celery

- name: Setup supervisor
  hosts: all
  sudo: yes
  roles:
    - role: supervisor