---

- name: Update server and install utils
  hosts: all
  sudo: yes
  roles:
    - role: common

- name: Install packages needed for python development
  hosts: all
  roles:
    - role: python-utils

- name: Set up nginx
  hosts: all
  roles:
    - role: nginx

- name: Set up PostgreSQL
  hosts: all
  sudo: yes
  roles:
    - role: postgresql

- name: Deployment
  hosts: all
  roles:
    - role: deployment
