---

- name: Defining users
  hosts: all
  sudo: yes
  roles:
    - role: users

- name: Update server and install utils
  hosts: all
  sudo: yes
  roles:
    - role: common

- name: Install packages needed for python development
  hosts: all
  sudo: yes
  roles:
    - role: python-utils

- name: Set up nginx
  hosts: all
  sudo: yes
  roles:
    - role: nginx

- name: Set up PostgreSQL
  hosts: all
  sudo: yes
  roles:
    - role: postgresql

- name: Setup webapp
  hosts: all
  sudo: yes
  roles:
    - role: webapp
