---

- name: Update server and install utils
  hosts: all
  roles:
    - role: common

- name: Install packages needed for python development
  hosts: all
  roles:
    - role: python-utils

- name: Set up nginx
  hosts: all
  roles:
    - role: nginx
