---

# Previously implemented SSH agent forwarding inside users role.
- name: read-write git checkout from repo  
  sudo_user: "{{ user }}"                                 
  git: 
    repo: "{{ repository }}" 
    dest: "/home/{{ user }}/{{ repository_name }}"
    version: "{{ deployment_branch }}"
    key_file: "/home/{{ user }}/.ssh/id_rsa"
    accept_hostkey: yes

- name: create virtualenv 
  sudo_user: "{{ user }}"
  shell: "virtualenv venv"
  args:
    chdir: "/home/{{ user }}"

- name: install requirements into virtualenv 
  sudo_user: "{{ user }}"
  raw: "source /home/{{ user }}/venv/bin/activate && cd /home/{{ user }}/{{ repository_name }} && pip install -r requirements.txt"

- name: copy api keys 
  sudo_user: "{{ user }}" 
  copy: 
    src: '{{ api_key_filepath }}'
    dest: "/home/{{ user }}/venv/.env"

# Add enviroment variables
- name: add enviroment variables to virtualenv
  sudo_user: "{{ user }}"
  raw: "cat $HOME/venv/.env >> $HOME/venv/bin/activate"

- name: add enviroment variables to user env
  sudo_user: "{{ user }}"
  raw: "cat $HOME/venv/.env >> $HOME/.bashrc"